[package]
name = "csvquery"
version = "0.1.0"
authors = ["VictorBulba <bulba@asclet.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "*"
serde = "*"
lru = "*"